### ISSUE TITLE
More robust templating

### ISSUE THREAD

**Issue by enzy** [frontbase/Frontbase#14]
Or another static site generators like (by priority):
- https://github.com/assemble/assemble v0.5
- https://github.com/segmentio/metalsmith
- https://github.com/jnordberg/wintersmith

**Comment by enzy** [comment]
What @ViliamKopecky feel about this?

**Comment by ViliamKopecky** [comment]
Do we make enough static websites to use this? And for my own prototyping, I'm quite happy with ristretto :P

**Comment by enzy** [comment]
Some sort of template structuring is required even in non static projects. And would be great to use same templates on backend either.
Don't take me wrong, Latte is great, but is not for node.js, which I would like to be one and only Frontbase requirement.

**Comment by ViliamKopecky** [comment]
If it will be optional via yeoman, than I have no complaints :)
